name: Build and Push Docker Images

on:
  push:
    branches:
      - staging
      - prod
  create:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: |
          if [[ "${{ github.ref }}" == refs/heads/staging ]]; then
            echo "IMAGE_TAG=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/prod ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/djangoindia-backend:${{ env.IMAGE_TAG }} -f backend/Dockerfile.prod ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/djangoindia-backend:${{ env.IMAGE_TAG }}

      - name: Logout from Docker Hub
        run: docker logout
